#!/bin/bash

# Assign the path of the .java file.
path="$1"

# Compile the file.
javac "$path"

# Replace '.java' with '',
# replace './' with '', and
# execute the .class file.
path="${path/.java/}"
path="${path/.\//}"
java "$path"
